include: package:flutter_lints/flutter.yaml

linter:

  rules:
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors: false
    sized_box_for_whitespace: false
    avoid_unnecessary_containers: false